ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-json
    exclude: |
      (?x)^(
        \.vscode/.*\.json
      )$
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
        tap_service_titan/openapi_specs/.*\.json|
        tests/snapshots/.*/.*/.*\.json
      )$
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.34.1
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.9.5
  hooks:
  - id: uv-lock
  - id: uv-sync
